<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="obj/Flutter.props" />

  <ItemGroup>
    <FlutterEphemeral Include="flutter\ephemeral\**\*" />
    <TizenTpkUserIncludeFiles Include="@(FlutterEphemeral)">
      <TizenTpkSubDir>%(RecursiveDir)</TizenTpkSubDir>
    </TizenTpkUserIncludeFiles>
  </ItemGroup>

</Project>
