<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <TargetFramework Condition="'$(TizenCoreEnabled)' == 'true'">net8.0-tizen10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(FlutterEmbeddingPath)" />
  </ItemGroup>

</Project>
