name: Dart

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install flutter-tizen
        run: echo `pwd`/bin >> $GITHUB_PATH
      - name: Install pub dependencies
        run: flutter-tizen pub get
      - name: Verify formatting
        run: flutter/bin/dart format --output=none --set-exit-if-changed lib
      - name: Analyze project source
        run: flutter/bin/dart analyze --fatal-infos lib
      - name: Run tests
        run: FLUTTER_ROOT=flutter flutter-tizen test
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: $env:FLUTTER_ROOT="flutter"; bin\flutter-tizen test
